apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-cfg
  namespace: "{{ .Values.global.helm_namespace }}"
data:
  oauth2-proxy.cfg: |
    # List of TLS cipher suites based on https://developers.cloudflare.com/ssl/edge-certificates/additional-options/cipher-suites/recommendations/#modern
    tls_cipher_suites = [
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
      "TLS_AES_128_GCM_SHA256",
      "TLS_AES_256_GCM_SHA384",
      "TLS_CHACHA20_POLY1305_SHA256"
    ]
